version: '3.9'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-app
    command: npm run dev
    working_dir: /app
    volumes:
      # Mount your project source into the container
      - .:/app
      # Keep node_modules container-only (to avoid OS/node ABI mismatch)
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/webdev
    depends_on:
      - postgres

  postgres:
    image: pgvector/pgvector:pg17-trixie # postgres with pg-vector - vector database
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webdev
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
